#pragma once

// Beaver triples + secure multiplication on additive secret shares.
// R34b + R34c deliverables — foundation for the MPC private join.
//
// SPDZ-style Beaver multiplication: given shares <x>, <y> of secret x, y,
// and a pre-generated correlated random triple <u>, <v>, <w> with w = u*v
// (mod 2^64), parties can compute shares of x*y via:
//
//   d := <x> - <u>    (opened: parties exchange shares, get plaintext d)
//   e := <y> - <v>    (opened)
//   <xy> := <w> + d * <v> + e * <u> + d * e   (each step local except the
//                                              two openings above)
//
// Privacy: d and e are uniformly random in the view of any adversary
// holding at most n-1 shares of x and y, because u and v are uniform
// randomness. Opening them leaks nothing.
//
// In this simulation, the Beaver triples are generated by a TRUSTED
// DEALER (placeholder for real OLE/VOLE generation in libOTe — that
// substitution is R34/R28-level engineering and is what makes the wire
// protocol secure).

#include "MpSecretShare.h"

#include "cryptoTools/Crypto/PRNG.h"

#include <cstdint>
#include <vector>

namespace volePSI {
namespace mpstar {

// One Beaver triple (u, v, w = u*v mod 2^64), each shared across N parties.
struct BeaverTripleU64 {
    SharedU64 u;
    SharedU64 v;
    SharedU64 w;   // w.reconstruct() == u.reconstruct() * v.reconstruct() (mod 2^64)
};

// Trusted-dealer Beaver-triple generator. Picks u, v uniformly random,
// computes w = u*v, distributes additive shares of all three to N parties.
// In a real protocol this is replaced by an OLE-based generator (libOTe
// SilentVole) — that's R34/R28 wire-level engineering.
BeaverTripleU64 generateBeaverTriple(uint32_t N, oc::PRNG& prng);

// Convenience: generate a batch of Beaver triples in one call.
std::vector<BeaverTripleU64>
generateBeaverTriples(uint32_t N, size_t count, oc::PRNG& prng);

// SPDZ Beaver-multiplication.
//
// Inputs:
//   x, y   : additive shares of secret values
//   triple : a fresh Beaver triple (one-shot; do not reuse)
//
// Output: additive shares of (x * y) mod 2^64. Consumes the triple.
//
// In this in-memory simulation, the "opening" of d and e is performed
// by reconstructing the SharedU64 values directly. In a wire protocol,
// each party broadcasts its share of d and e; the resulting plaintext
// is identical.
SharedU64 secureMultiply(const SharedU64& x,
                         const SharedU64& y,
                         const BeaverTripleU64& triple);

// Boolean (XOR-shared) variant. A Beaver triple over Z_2 is just three
// bits (u, v, w=u·v over Z_2 = u AND v) shared additively-mod-2.
struct BeaverTripleBit {
    SharedBit u;
    SharedBit v;
    SharedBit w;   // w.reconstruct() == u.reconstruct() & v.reconstruct()
};

BeaverTripleBit generateBeaverTripleBit(uint32_t N, oc::PRNG& prng);

std::vector<BeaverTripleBit>
generateBeaverTripleBits(uint32_t N, size_t count, oc::PRNG& prng);

// Secure AND of two XOR-shared bits via Beaver multiplication over Z_2.
// Consumes one triple.
SharedBit secureAnd(const SharedBit& x,
                    const SharedBit& y,
                    const BeaverTripleBit& triple);

} // namespace mpstar
} // namespace volePSI
