#pragma once

// R26b/step2: OT-based preprocessing for the CGP secret-shared shuffle
// (Chase-Ghosh-Poburinnaya, Asiacrypt 2020). Replaces the trusted-
// dealer correlation generator in MpCgpShuffle.h with a real 2-party
// protocol grounded in libOTe's SilentOtTriple over coproto sockets.
//
// The construction the trusted dealer produces:
//     A learns (a, alpha)  in RowVec × RowVec
//     B learns (pi, b)     with pi a permutation of [n]
//   invariant: alpha[i] = a[pi[i]] XOR b[i]  (row-wise)
//
// Our OT-based replacement uses OLE-friendly correlated randomness
// generated by libOTe's SilentOtTriple in the OLE mode. Each block of
// the correlation is produced by silent OT extension; the composition
// with the permutation network runs in a Benes-style layered routing
// where each switch consumes 1 OT.
//
// This module currently implements the PROTOCOL SCAFFOLDING with a
// two-party wire protocol; the correlation is derived from a shared
// seeded PRNG (via socket handshake). This is NOT cryptographically
// secure — it demonstrates the wire structure so the substitution to
// real silent-OT-derived correlation is a targeted change inside
// runPreprocessProtocol().
//
// SECURITY GAP: The seeded-PRNG variant here reveals the correlation
// structure to both parties (since both derive it from the shared
// seed). The libOTe substitution below is the security-completing
// step. Documented in docs/DESIGN.md and
// docs/DESIGN.md.

#include "MpCgpShuffle.h"
#include "cryptoTools/Crypto/PRNG.h"

#include "coproto/Socket/Socket.h"
#include "macoro/task.h"

#include <cstdint>

namespace volePSI {
namespace mpstar {

// Bundled per-party output from the CGP preprocessing wire protocol.
struct CgpPreprocResult {
    bool isPartyA;                 // true if this party is the receiver-role (A)
    CgpCorrelationA partyA;        // valid when isPartyA == true
    CgpCorrelationB partyB;        // valid when isPartyA == false
};

// Two-party CGP preprocessing over a coproto socket.
//   partyIdx: 0 = A (receiver-role, learns a + alpha)
//             1 = B (sender-role, learns pi + b)
//   n: number of rows in the permutation
//   W: row width in blocks
//   prng: local randomness source; also seeded from the shared handshake
//   sock: connected coproto::Socket to the peer
//
// Returns this party's half of the correlation. The peer receives the
// complementary half. Both halves together satisfy the CGP invariant
// alpha[i] = a[pi[i]] XOR b[i] row-wise.
macoro::task<CgpPreprocResult> cgpPreprocessOverWire(
    uint64_t partyIdx,
    uint32_t n, uint32_t W,
    oc::PRNG& prng,
    coproto::Socket& sock);

} // namespace mpstar
} // namespace volePSI
