#pragma once

// R36c: 2-party wire-protocol end-to-end SP-blind MPC private join.
// Composes MpMpcWireOps primitives (wireMpcBitonicSort +
// wireMpcCrossProductExpand + wireMpcFilterIntersection). Each party
// holds its own bit-shared input tables and drives its half of the
// protocol via a coproto::Socket.
//
// Semi-honest 2-party. Beaver triples are pre-generated by the caller
// (via R34k oleGenerateTriples for real security, or by trusted-dealer
// generateBeaverTripleBit for tests). Triple bag size = returned by
// wireMpcExecutePrivateJoinTripleCost.

#include "MpMpcWire.h"
#include "MpMpcWireOps.h"
#include "MpBeaverTriple.h"

#include "coproto/Socket/Socket.h"
#include "macoro/task.h"

#include <cstdint>
#include <vector>

namespace volePSI {
namespace mpstar {

// One party's shared input row (bit-shared 64-bit id + bit-shared payload
// + bit-shared is_real).
struct WireJoinInputRow {
    std::array<uint8_t, 64> id;
    uint8_t isReal;
    std::vector<uint8_t> rowData;  // length rowDataBits
};

// Wire end-to-end driver. Both parties call this in cooperating
// coroutines. Each party's `myTable[p][r]` is party p's r-th tuple share
// as visible to THIS party (i.e., each party sees ITS OWN half of every
// tuple).
//
// Pad-input contract (same as mpcExecutePrivateJoinInMemory): every
// perParty[p].size() == universeSize * M. Padding + party_idx tagging
// is done by the caller (matches R34g-j in-memory pattern).
//
// Returns: this party's shares of the joined output rows.
macoro::task<std::vector<WireMpcJoinRow>> wireMpcExecutePrivateJoin(
    uint32_t N, uint32_t M,
    uint32_t partyIdxBits, uint32_t rowDataBits,
    const std::vector<std::vector<WireJoinInputRow>>& myTable,
    const std::vector<BeaverTripleBit>& triples,
    uint64_t partyIdx,
    coproto::Socket& sock);

// Triple count for the end-to-end driver (matches
// mpcExecutePrivateJoinInMemoryTripleCost structure but for wire ops).
size_t wireMpcExecutePrivateJoinTripleCost(
    uint32_t N, uint32_t M,
    uint32_t partyIdxBits, uint32_t rowDataBits,
    size_t universeSize);

} // namespace mpstar
} // namespace volePSI
